name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::471112994860:user/temp.user
          aws-region: us-east-1

      - name: Deploy to EC2
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=INSTANCE_ID" \
            --parameters 'commands=["cd /home/ubuntu/your-repo", "git pull testing MASTER", "npm install", "npm run build", "pm2 serve build 3000 --spa"]'
