name: Deploy React App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.X'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
          EC2_PUBLIC_IP: ${{ secrets.EC2_IP }}
          EC2_USER: ubuntu
          EC2_KEY_PATH: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          sshpass -p ${{ secrets.EC2_PASSWORD }} scp -o StrictHostKeyChecking=no -r build/* $EC2_USER@$EC2_PUBLIC_IP:/home/ubuntu/your-repo/build
          sshpass -p ${{ secrets.EC2_PASSWORD }} ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_PUBLIC_IP 'sudo systemctl restart nginx'
