name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ec2-52-23-45-211.compute-1.amazonaws.com
          username: ubuntu
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAgEA1MRhEAul+VLFYkJAe6OKmkA2E9VCpL5RavIdZoRqMS3qxYV7kQJS
            qCa0szu7mWXm3Hl5jnHd8yuyW8/EFP83MhnZ3X6xJgPvTIhlU8Up7YIXRIWLKU3jBxqeWi
            4+8T8jzKXEUsUF8qSI4J5mOhH5tYSZBoIZ3bRbVtXPv+U3AiqbFYf3cZV2hhCSS4LXJk+1
            LIBwUWjXBr2WA8ly6nEZh2zbnb1/UPXc6fATQ023T8Pn/HwhsWzBjbnUgKLoVu9fbLyPIU
            P09Ug3yPmwA0QGnOJndaJPFtZPGCqo4U/F+B7j3RhxvWnFlTbt9n5X/sKuTcZU1TLKSK99
            pDxMF32yNRLIhD6cfd1B2zvWF7JF6h568h1G1G8keFl2TtKZn9yKFJdpRCl5eR/nLmVeP9
            1akkmXfFWDRgWBaFr9SCW3NxNIw0T2JXKos3RRTSMtpONp74sQmp6ed+ACAuuSSVZHm6vi
            jU9310Az7c8+ebIvTu1bZ+XjURHOfxINnie3gyJ7QkJK5nDv0H2+HF3tXymK5ZxhnaQcxm
            8yBeU9SNEW0R+2EU36lGmDuYY6zKlXKQQlJbVxeT0pwTNLDp75JzpnkFkHIiYSmzi/upfe
            kLCjwL4Nf/FYIwDoNrX2/kL2rhUblxLEt9/sOJrPq5i03Juew+33Ymuh4dMSBngaRumLRl
            EAAAdgvA4FrbwOBa0AAAAHc3NoLXJzYQAAAgEA1MRhEAul+VLFYkJAe6OKmkA2E9VCpL5R
            avIdZoRqMS3qxYV7kQJSqCa0szu7mWXm3Hl5jnHd8yuyW8/EFP83MhnZ3X6xJgPvTIhlU8
            Up7YIXRIWLKU3jBxqeWi4+8T8jzKXEUsUF8qSI4J5mOhH5tYSZBoIZ3bRbVtXPv+U3Aiqb
            FYf3cZV2hhCSS4LXJk+1LIBwUWjXBr2WA8ly6nEZh2zbnb1/UPXc6fATQ023T8Pn/HwhsW
            zBjbnUgKLoVu9fbLyPIUP09Ug3yPmwA0QGnOJndaJPFtZPGCqo4U/F+B7j3RhxvWnFlTbt
            9n5X/sKuTcZU1TLKSK99pDxMF32yNRLIhD6cfd1B2zvWF7JF6h568h1G1G8keFl2TtKZn9
            yKFJdpRCl5eR/nLmVeP91akkmXfFWDRgWBaFr9SCW3NxNIw0T2JXKos3RRTSMtpONp74sQ
            mp6ed+ACAuuSSVZHm6vijU9310Az7c8+ebIvTu1bZ+XjURHOfxINnie3gyJ7QkJK5nDv0H
            2+HF3tXymK5ZxhnaQcxm8yBeU9SNEW0R+2EU36lGmDuYY6zKlXKQQlJbVxeT0pwTNLDp75
            JzpnkFkHIiYSmzi/upfekLCjwL4Nf/FYIwDoNrX2/kL2rhUblxLEt9/sOJrPq5i03Juew
            +33Ymuh4dMSBngaRumLRlEAAAADAQABAAACAQC+eSejo6nsL+tAcaskhF3ahU1kJ/DHZx
            GgOiuT0Ur3x/F67mqWgIvauPvf0MO7Kfyot57YpJtbzGyZwL/7RBb3pSjjHz4bmD4sN5b
            ujX1hgKqvzxWr3mw1ueC1Pt1eP3YfCO9eYb9XX3CiFWvS5LC1jYUozGO3lHSIolSfp+W8
            7MN1XQlqB7HZhxBQxUsyovzAYCMs3jxRbnvT3A4iTynZkNxytGg75D7mtuOnxvUqVWljI
            QVQvtnvtMLGfhCdcyHsSEmiMCIlS4eVReIKqmV5IT4ZkzpWaXjZW6dgPXgvDghTsERymz
            Qkxs31c1n3WfWM7taXHib1NxW1Z71+8ioLsyLcgVobbOiNkQ0Ez4lm3uO/VwaCR/9JQ9a
            IBK5jvsJO8+QRb7xn49PbdUMkMhg4v4FEK2PKThjDrsVUknhst3+nQmA6uA7qmndBHs51
            iBSWsLumXSltrMT9B6/Phg5DH1ngoj7PccIbLpi0Qh9/Kkn5ELq/EWQjBf6/Dy0CUPiG
            VgR7j9Nqw94GXk/ZnCe0TmsmeRLlR/4bSBvIgubF6xD/KCXq2Htrnhi28dYUNwhOjrgY
            2KCAu+kjjm6xgEr9DDuz2JBLw4MbynT4y5GAuM02VAMIUkMpKvlnmdoei5mOk78RKQja
            s+k/SpOgfcLA1Yeesg2/6HMikfRfnoJNgQAAAQEAodYfFAw06l2wOly8iYF9EuiQnWM8
            IeHyTmkJlW+UI1GVKsrXBrcIEikf439Nn0KY5ZZSubAjZ7ta+Z4wn4HYIusUHJ9fY3Y8
            gmAovZS02iD3W80WJW1qgeBLCySOT9Ol55Lpgljk96i/TqunRdqxPF4tBMFRSgiZFLSW
            Fn1g96n3UUAYtGQ/eO8LFCZlEkXKBLit0Q6/sol+5AIpS4g9to1j7iCwKiNtji+1lIzz
            p6knDDsvMQhckusP+FPuyTntFG9ZWuP/nqkI3Hwr+lWj7vhctAqsy0j9trtNkgcRgYkd
            0fPF5Gj4QxoDOIQjC2MLQycoGpSfRfksNmEQwvfVwQAAAQEA8jznU6Ul5QjsFhqbMkCQ
            3Hh6id+BopSFXp+EvLS1FUx6EyMIph3t9EJzxSfywYc751kcOPyWO5/oYIhZMCVmLnCa
            xY6zIaemXwgue8YtlA5z2ZfoaKO3fheOwkp2I2RCNgQBuKyVG9GKiovkw1n9PZhRnR68
            bLwgvGPyUyEk6SXALzEhTZ1aLDI8yZ6rm6pKEbjGdcpwjnjEBPwT+Ksby6fPoPf85nZk
            KX2OYr7Vo3h/rjyvyYrTG6ll6VYdjTQzyEQeRXUggVryFjqDMh7N9TBhsGE8bRDGkFiJ
            kbHqcU3JqyXzQ+t8IeWB7PBfXiCC4UU5xC86WfUMkc2ugbSGGQAAAQEA4NraiWOxIG0/
            xpuiWrr+p7nrnwCNG/OhLclt6HO82CBwoJaZrQdU9W8P/HyHJ2DCiTDyQ76TBFQBQkPW
            5oC5Sc/CfYD+Z/dBvAddgzvHQO50yNuVS6YkSsey+3zMyz24BEk0OYiI57NFrDuJPEaY
            g5dDlPZS++OigfPBx1KHP6YGPUGTIdfQQEgHxfzujBUogTX3Uhhuhu/AIBYg26uTdd4y
            fHnQD0gQcLafsvfo7G50YIWbhPsxO/zfpX3B3kubgaKPVr+4yDTVJ0WP+70RqtgLAYGR
            VmGRZ3OGu+Pr45QpRktPVG0Ac1jkQA7CFqLaAuTO22NAaLPJsmWd6saY+QAAACZoaW50
            b25icm90aGVyc3ByaXZhdGVsaW1pdGVkQGdtYWlsLmNvbQECAw==
            -----END OPENSSH PRIVATE KEY-----
          port: 22
          script: |
            cd /etc/nginx/htdocs/build
            git pull testing.app master
            # Example: Restart your server (replace with your actual deployment steps)
            pm2 restart my-app

